### PR TITLE
Allow Hadoop up to 2.4, spark up to 1.2.0. Set 1.2.0 as default spark version

### PR DESCRIPTION
**Pull request by luisguilherme**

### CODE REVIEW

**Comment by luisguilherme** [comment]
Another friendly ping, @douglaz

**Comment by luisguilherme** [comment]
(with spark 1.2.0, the disk space error vanished. We should move ASAP to it)

**Comment by douglaz** [comment]
Did you test a big MailBuilder job with 1.2.0?

**Comment by luisguilherme** [comment]
I did test User History and Price Reduced jobs, both with success)

Changing the default here, however, doesn't change the actual default, since it's set by job_runner.py script. It's safe to merge this, if we keep mail builder using 1.0.2 via job_runner.py script.

**Comment by douglaz** [comment]
But even using 1.0.2 and hadoop 1 it may break because the chaordic branch changed (for instance, the cluster may have a bogus configuration that only break with a job like MailBuilder). So I would wait a more complete test  before merging.

**Comment by luisguilherme** [comment]
All set! 48h triggers processed in 3h

**Pull request merged**
