### PR TITLE
Adds an option to launch the cluster master as spot

### PR DESCRIPTION
**Pull request by mwconceicao**
This PR adds an option to launch the cluster master instance as spot, decreasing a little bit the total cost of the cluster. Some jobs, sometimes, worth doing this.

### CODE REVIEW

**Comment by raittes** [comment]
LGTM

**Comment by mwconceicao** [comment]
@douglaz @zago @fparisotto @fernandors87 Some of you wanna take a look too?

**Comment by fparisotto** [comment]
I agree about duplicated code, but we can do that later, as @douglaz says.
If this change was tested and is working, LGTM.

**Comment by mwconceicao** [comment]
TODO added, later I will refactor that part of the code.

**Pull request merged**
